import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css' //the @ means start at the root
import Ad from '@/components/Ad'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>Welcome to the Home Page</h1>
        <Ad/>
      </main>
    </>
  )
}
